services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

  ai-service:
    build: ./Python-aiservice
    env_file: ./Python-aiservice/.env
    volumes:
      - chroma_data:/app/chroma_db
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  backend:
    build: ./Backend
    env_file: ./Backend/.env
    environment:
      PORT: "5000"
      MONGODB_URI: mongodb://mongo:27017/codeassistant
      AI_SERVICE_URL: http://ai-service:8000
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_started
      ai-service:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL:http://13.233.101.108:5000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  chroma_data: